# FOR SIDEKIQ TO WORK PROPERLY WITH SIDEKIQ-CRON, THERE ALWAYS MUST BE AT LEAST ONE JOB
# FEEL FREE TO REMOVE THIS CLASS (AND ITS CORREPSONDING CRON) ONCE YOU'VE WRITTEN YOUR OWN
# TO CREATE NEW JOBS, RUN `bin/r new_worker NewJobNameHere` IN YOUR CLI

class PlaceholderJob
  include Sidekiq::Job

  def perform(*args)
    puts "REPLACE THIS CLASS WITH A REAL JOB"
  end
end
